CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content TEXT,
    owner_id BIGINT,
    last_edited_by_id BIGINT,
    version BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_document_owner
        FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_document_last_edited_by
        FOREIGN KEY (last_edited_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS document_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT uk_document_access_document_user
        UNIQUE (document_id, user_id),
    CONSTRAINT fk_document_access_document
        FOREIGN KEY (document_id) REFERENCES document(id),
    CONSTRAINT fk_document_access_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    document_version_number BIGINT NOT NULL,
    content_snapshot TEXT NOT NULL,
    edited_by_id BIGINT,
    edited_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_document_version_document
        FOREIGN KEY (document_id) REFERENCES document(id),
    CONSTRAINT fk_document_version_edited_by
        FOREIGN KEY (edited_by_id) REFERENCES users(id)
);
